name: Build Docker Image

on:
  workflow_dispatch:  
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Login into Github Docker Registery
          run: echo "${{ secrets.ghToken }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

        - name: Install Shopware-CLI
          uses: FriendsOfShopware/shopware-cli-action@v1
        
        - name: Generate jwt-private
          run: echo "${{ shopware-cli project generate-jwt --env }}"
  
  # build:
  #   uses: shopware/github-actions/.github/workflows/build-docker-image.yml@main
  #   with:
  #     bun-version: '1.0.22'
  #   secrets:
  #     ghToken: ${{ secrets.GITHUB_TOKEN }}
