name: Smoke test Image
on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout example repo
        uses: actions/checkout@v4
        with:
          path: example-repo
          repository: shopwareLabs/example-docker-repository

      - name: Build
        id: build
        uses: docker/build-push-action@v5
        with:
          push: false
          load: true
          tags: |
            shopware/docker-base:8.3
            docker.io/shopware/docker-base:8.3
          context: 8.3/
          file: 8.3/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run image
        env:
          DOCKER_BUILDKIT: 0
        working-directory: example-repo
        run: docker compose up -d --wait

      - name: Check if shopware is running
        run: curl --fail localhost:8000/admin

      # output logs if failed
      - name: Output logs
        working-directory: example-repo
        run: docker compose logs
        if: ${{ failure() }}
