name: Generate Images
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  update:
    name: Generate Builds
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Generate files
        run: |
          php generate.php

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.CI_PUSH_TOKEN }}
          commit-message: 'New docker updates'
          delete-branch: true
          assignees: shyim
          reviewers: shyim
